PROJECT_ENV_NAME = "NEPTUNE_PROJECT"
API_TOKEN_ENV_NAME = "NEPTUNE_API_TOKEN"
ALLOW_SELF_SIGNED_CERTIFICATE = "NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE"

DISABLE_COLORS = "NEPTUNE_DISABLE_COLORS"
DEBUG_MODE = "NEPTUNE_DEBUG_MODE"

SUBPROCESS_KILL_TIMEOUT = "NEPTUNE_SUBPROCESS_KILL_TIMEOUT"

# Default timeout used to wait for operations to be processed by the Neptune backend.
# Affects Run.wait*() and Run.close*() methods.
OPERATIONS_TIMEOUT_SECONDS = "NEPTUNE_OPERATIONS_TIMEOUT_SECONDS"
