"""Constants used for generating human-readable run IDs."""

RUN_ID_ADJECTIVES = [
    # Size/Scale related
    "tiny",
    "small",
    "large",
    "mega",
    "micro",
    "giant",
    "nano",
    "vast",
    "colossal",
    "atomic",
    "massive",
    # Speed related
    "swift",
    "rapid",
    "fast",
    "quick",
    "agile",
    "turbo",
    "sonic",
    "instant",
    "nimble",
    # Intelligence/Capability related
    "smart",
    "wise",
    "clever",
    "sharp",
    "bright",
    "neural",
    "deep",
    "learned",
    "trained",
    "evolved",
    # Efficiency related
    "optimal",
    "efficient",
    "lean",
    "precise",
    "exact",
    "tuned",
    "refined",
    "balanced",
    "scaled",
    # Performance related
    "robust",
    "stable",
    "dynamic",
    "adaptive",
    "flexible",
    "parallel",
    "resilient",
    "reliable",
    "smooth",
    # Quality related
    "fine",
    "refined",
    "premium",
    "elite",
    "prime",
    "pure",
    "ideal",
    "perfect",
    # Scientific related
    "quantum",
    "atomic",
    "neural",
    "cosmic",
    "binary",
    "digital",
    "linear",
    # Color-based
    "blue",
    "green",
    "red",
    "silver",
    "golden",
    "azure",
    "crystal",
]

RUN_ID_NOUNS = [
    # Animals known for intelligence
    "dolphin",
    "raven",
    "octopus",
    "elephant",
    "owl",
    "chimp",
    "falcon",
    "wolf",
    # Scientific/Mathematical terms
    "tensor",
    "vector",
    "matrix",
    "graph",
    "neuron",
    "scalar",
    "gradient",
    "kernel",
    "entropy",
    "qubit",
    "lattice",
    "manifold",
    # Cosmic objects
    "nova",
    "nebula",
    "star",
    "cosmos",
    "aurora",
    "quasar",
    "pulsar",
    "photon",
    # Greek letters
    "alpha",
    "beta",
    "gamma",
    "delta",
    "sigma",
    "omega",
    "lambda",
    "epsilon",
    # Elements and materials
    "carbon",
    "xenon",
    "neon",
    "titan",
    "argon",
    "silicon",
    "quantum",
    "plasma",
    # Abstract concepts
    "mind",
    "logic",
    "spark",
    "core",
    "apex",
    "vision",
    "wisdom",
    "insight",
    # Technology terms
    "node",
    "pixel",
    "byte",
    "flux",
    "quantum",
    "cache",
    "thread",
    "stream",
    "cipher",
    "neural",
    # ML/AI specific
    "epoch",
    "batch",
    "model",
    "layer",
    "agent",
    "learner",
    "encoder",
    "decoder",
]
