---
name: Test Unit
description: Check unit tests
inputs:
  python-version:
    description: "Python version"
    required: true
  os:
    description: "Operating system"
    required: true
  report_job:
    description: "Job name to update by JUnit report"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install package
      uses: ./.github/actions/install-package
      with:
        python-version: ${{ inputs.python-version }}
        os: ${{ inputs.os }}-latest

    - name: Test
      run: |
        pytest -v --timeout=120 --timeout_method=thread \
        --color=yes \
        --junitxml="./test-results/test-unit-new-${{ inputs.os }}-${{ inputs.python-version }}.xml" \
        ./tests/unit/ ./src/
      shell: bash

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-artifacts-${{ inputs.os }}-${{ inputs.python-version }}
        path: ./test-results

    - name: Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: './test-results/test-unit-*.xml'
        update_check: true
        include_passed: true
        job_name: ${{ inputs.report_job }}
