name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    timeout-minutes: 10

    runs-on: tools-gha-runners
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
