name: e2e tests

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: # Don't run e2e tests on PRs that don't modify source code
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: arc-runner-set
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      - name: Run tests
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.E2E_API_TOKEN }}
          NEPTUNE_E2E_PROJECT: ${{ secrets.E2E_PROJECT }}
          NEPTUNE_E2E_CUSTOM_RUN_ID: ${{ vars.E2E_CUSTOM_RUN_ID }}
        run: pytest --junitxml="test-results/test-e2e-${{ matrix.python-version }}.xml" tests/e2e

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts-${{ matrix.python-version }}-${{ github.run_id }}
          path: "./test-results/"

      - name: Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "./test-results/test-e2e*.xml"
          update_check: true
          include_passed: true
          annotate_notice: true
          job_name: "e2e tests"
